./waf --run "scratch/taskA_1 --first=true --type=NODE --nNodes=20";
./waf --run "scratch/taskA_1 --type=NODE --nNodes=40";
./waf --run "scratch/taskA_1 --type=NODE --nNodes=60";
./waf --run "scratch/taskA_1 --type=NODE --nNodes=80";
./waf --run "scratch/taskA_1 --type=NODE --nNodes=100";
./waf --run "scratch/taskA_1 --first=true --type=FLOW --nFlows=10";
./waf --run "scratch/taskA_1 --type=FLOW --nFlows=20";
./waf --run "scratch/taskA_1 --type=FLOW --nFlows=30";
./waf --run "scratch/taskA_1 --type=FLOW --nFlows=40";
./waf --run "scratch/taskA_1 --type=FLOW --nFlows=50";
./waf --run "scratch/taskA_1 --first=true --type=SPEED --nodeSpeed=5.0";
./waf --run "scratch/taskA_1 --type=SPEED --nodeSpeed=10.0";
./waf --run "scratch/taskA_1 --type=SPEED --nodeSpeed=15.0";
./waf --run "scratch/taskA_1 --type=SPEED --nodeSpeed=20.0";
./waf --run "scratch/taskA_1 --type=SPEED --nodeSpeed=25.0";
./waf --run "scratch/taskA_1 --first=true --type=PacketsPerSec --packetsPerSec=100";
./waf --run "scratch/taskA_1 --type=PacketsPerSec --packetsPerSec=200";
./waf --run "scratch/taskA_1 --type=PacketsPerSec --packetsPerSec=300";
./waf --run "scratch/taskA_1 --type=PacketsPerSec --packetsPerSec=400";
./waf --run "scratch/taskA_1 --type=PacketsPerSec --packetsPerSec=500";
python plotGraphTaskA1.py;
